version: '3.8'

# Services
services:

    # Nginx Service
    nginx:
        image: nginx:1.21
        ports:
            - "8082:8082"
            - "8081:8081"
        volumes:
            - ./api:/var/www/kava_project
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - app

    # PHP Service
    php:
        build: ./docker/php
        working_dir: /var/www/kava_project
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./api:/var/www/kava_project
            - ./docker/php/php-dev.ini:/usr/local/etc/php/conf.d/php-dev.ini
        depends_on:
            mysql:
                condition: service_healthy

    # MySQL Service
    mysql:
        image: mysql/mysql-server:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_USER: "kava"
            MYSQL_PASSWORD: "1234"
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "kava_fin_mon"
        volumes:
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - mysqldata:/var/lib/mysql
        healthcheck:
            test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
            interval: 5s
            retries: 10
        ports:
            - '3308:3306'

    # PHPMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5
        ports:
            - 8888:80
        environment:
            PMA_HOST: mysql
        depends_on:
            mysql:
                condition: service_healthy

    app:
        build:
            context: ./app
        ports:
            - "3000:3000"

    init:
        build:
            context: docker/init
        volumes:
            - ./api:/var/www/kava_project
            - ./docker/init/init.sh:/init.sh
        command: bash -c "cat /init.sh | bash"
        depends_on:
            - php
# Volumes
volumes:
    mysqldata:
