version: '3.8'

# Services
services:

    # Nginx Service
    nginx:
        image: nginx:1.21
        ports:
            - "8082:8082"
            - "8081:8081"
        volumes:
            - ./api:/var/www/kava_project
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - api
            - app

    # PHP Service
    api:
        build: ./docker/php
        working_dir: /var/www/kava_project
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./api:/var/www/kava_project
            - ./docker/php/php-dev.ini:/usr/local/etc/php/conf.d/php-dev.ini
        depends_on:
            redis:
                condition: service_started
            mysql:
                condition: service_healthy

    # MySQL Service
    mysql:
        image: mysql/mysql-server:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_USER: "kava"
            MYSQL_PASSWORD: "1234"
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "kava_fin_mon"
        volumes:
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - mysqldata:/var/lib/mysql
        healthcheck:
            test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
            interval: 5s
            retries: 10
        ports:
            - '3308:3306'

    # PHPMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5
        ports:
            - 8888:80
        environment:
            PMA_HOST: mysql
        depends_on:
            mysql:
                condition: service_healthy

    app:
        container_name: app
        build:
            context: ./app
        volumes:
            - ./app/source/src:/var/www/kava_project_front/src
        ports:
            - "3000:3000"

    init:
        build:
            context: docker/init
        volumes:
            - ./api:/var/www/kava_project
            - ./docker/init/init.sh:/init.sh
        command: bash -c "cat /init.sh | bash"
        depends_on:
            - api

    messenger:
        build:
            context: ./docker/supervisord
        working_dir: /var/www/kava_project
        depends_on:
            - mysql
            - redis
        volumes:
            - ./api:/var/www/kava_project
            - ./docker/supervisord/supervisord.conf:/etc/supervisor/conf.d/supervisor.conf
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
                max-file: "3"

    redis:
        image: "redis:6-alpine"
        ports:
            - "6379:6379"
        volumes:
            - ./storage/redis:/redis

    node:
        build: node
        depends_on:
            - redis
        volumes:
            - ./node/source/src:/var/www/kava_project_node/src
        ports:
            - "9100:9000"
# Volumes
volumes:
    mysqldata:
