framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 5
                    delay: 2000
                    multiplier: 2
                    max_delay: 0
            sync: 'sync://'

        routing:
            'App\Domain\Contract\Command\SyncCommandInterface': sync
            'App\Domain\Contract\Command\AsyncCommandInterface': async
