security:
    enable_authenticator_manager: true

    providers:
        jwt:
            lexik_jwt: ~

    firewalls:
        login:
            pattern: /v1/auth
            stateless: true

        api:
            pattern: ^/v1
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/v1/auth, roles: PUBLIC_ACCESS }
        - { path: ^/v1, roles: IS_AUTHENTICATED_FULLY }

    password_hashers:
        App\Domain\Entity\User: 'auto'

        # auto hasher with custom options for all PasswordAuthenticatedUserInterface instances
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            cost: 15
