lexik_jose:
    ttl: 3600
    server_name: '%env(resolve:SL_JOSE_BRIDGE_SERVER_NAME)%'
    key_set: '%env(LEXIK_JOSE_SIGNATURE_KEYSET)%'
    key_index: 0
    encryption:
        enabled: true
        key_set: '%env(LEXIK_JOSE_ENCRYPTION_KEYSET)%'
        key_index: 0
        key_encryption_algorithm: 'A256GCMKW'
        content_encryption_algorithm: 'A256GCM'
    signature_algorithm: "RS256"
    mandatory_claims:
        - 'exp'
        - 'iat'
        - 'iss'
        - 'aud'
    claim_checked:
        - 'auth_user_claim'
