#controllers:
#    resource: ../src/Controller/
#    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

operations:
    path: /operation
    controller: App\Controller\OperationController::list
    methods: GET